# Generated by Django 2.2.7 on 2019-11-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('namora', models.BooleanField(default=True, verbose_name='Namoro')),
                ('entrar_CITi', models.CharField(blank=True, max_length=30, null=True, verbose_name='CITi')),
            ],
        ),
    ]
