# Generated by Django 2.2.7 on 2019-11-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300, verbose_name='Link')),
                ('image', models.ImageField(upload_to='imagens/', verbose_name='Imagem')),
            ],
        ),
        migrations.RemoveField(
            model_name='pessoal',
            name='nome',
        ),
        migrations.AlterField(
            model_name='pessoal',
            name='entrar_CITi',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='citi'),
        ),
        migrations.AlterField(
            model_name='pessoal',
            name='idade',
            field=models.IntegerField(verbose_name='idade'),
        ),
        migrations.AlterField(
            model_name='pessoal',
            name='namora',
            field=models.BooleanField(default=True, verbose_name='namoro'),
        ),
    ]
