# Generated by Django 2.2.7 on 2019-11-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191110_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemperfil',
            name='image',
        ),
        migrations.AddField(
            model_name='imagemperfil',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='imagemperfil',
            name='url',
            field=models.URLField(max_length=300, verbose_name='link'),
        ),
    ]
