# Generated by Django 2.2.7 on 2019-11-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoisasQueNaoSouBom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coisa', models.CharField(max_length=150)),
            ],
        ),
    ]
