# Generated by Django 2.2.7 on 2019-11-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coisasquenaosoubom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coisasquenaosoubom',
            old_name='coisa',
            new_name='atividade',
        ),
    ]
