# Generated by Django 2.2.7 on 2019-11-10 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191110_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coisasquenaosoubom',
            options={'verbose_name': 'Atividade que posso melhorar', 'verbose_name_plural': 'Atividades que posso melhorar'},
        ),
    ]
