# Generated by Django 2.2.7 on 2019-11-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191110_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemperfil',
            options={'verbose_name': 'Imagem de Perfil', 'verbose_name_plural': 'Imagens de Perfil'},
        ),
    ]
