# Generated by Django 2.2.7 on 2019-11-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191110_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoal',
            options={'verbose_name': 'Informação pessoal', 'verbose_name_plural': 'Informações pessoais'},
        ),
    ]
