# Generated by Django 2.2.7 on 2019-11-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191110_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entretenimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_obra', models.CharField(max_length=200, verbose_name='nome')),
                ('url_sobre_a_obra', models.URLField(max_length=400, verbose_name='link')),
            ],
            options={
                'verbose_name': 'Obra de entretenimento',
                'verbose_name_plural': 'Obras de entretenimento',
            },
        ),
    ]
