# Generated by Django 2.2.7 on 2019-11-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_entretenimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretenimento',
            name='url_sobre_a_obra',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='link'),
        ),
    ]
