# Generated by Django 2.2.7 on 2019-11-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191110_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretenimento',
            name='nome_da_obra',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='entretenimento',
            name='url_sobre_a_obra',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='atividade',
            field=models.CharField(max_length=100, verbose_name='Atividade'),
        ),
        migrations.AlterField(
            model_name='imagemperfil',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='upload_da_imagem'),
        ),
        migrations.AlterField(
            model_name='imagemperfil',
            name='url',
            field=models.URLField(max_length=400, verbose_name='Link da imagem'),
        ),
        migrations.AlterField(
            model_name='imagenscoisasquegosto',
            name='imagem_upload',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='Upload_da_imagem'),
        ),
        migrations.AlterField(
            model_name='imagenscoisasquegosto',
            name='url_imagem',
            field=models.URLField(max_length=400, verbose_name='Link_Imagem'),
        ),
        migrations.AlterField(
            model_name='imagenscoisasquegosto',
            name='url_sobre_a_imagem',
            field=models.URLField(max_length=400, verbose_name='Link_sobre_a_imagem'),
        ),
        migrations.AlterField(
            model_name='pessoal',
            name='entrar_CITi',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Pensamento_sobre_o_CITi'),
        ),
        migrations.AlterField(
            model_name='pessoal',
            name='idade',
            field=models.IntegerField(verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='pessoal',
            name='namora',
            field=models.BooleanField(default=True, verbose_name='Namoro'),
        ),
    ]
