# Generated by Django 2.2.7 on 2019-11-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191110_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemperfil',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='Upload da imagem'),
        ),
        migrations.AlterField(
            model_name='imagenscoisasquegosto',
            name='imagem_upload',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='Upload da imagem'),
        ),
        migrations.AlterField(
            model_name='imagenscoisasquegosto',
            name='url_imagem',
            field=models.URLField(max_length=400, verbose_name='Link Imagem'),
        ),
        migrations.AlterField(
            model_name='imagenscoisasquegosto',
            name='url_sobre_a_imagem',
            field=models.URLField(max_length=400, verbose_name='Link sobre a imagem'),
        ),
        migrations.AlterField(
            model_name='pessoal',
            name='entrar_CITi',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Pensamento sobre o CITi'),
        ),
    ]
