# Generated by Django 2.2.7 on 2019-11-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191110_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='atividade',
            field=models.CharField(max_length=100, verbose_name='Hobby'),
        ),
    ]
