# Generated by Django 2.2.7 on 2019-11-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191110_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemperfil',
            name='url',
        ),
    ]
