# Generated by Django 2.2.7 on 2019-11-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_imagemperfil_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemperfil',
            name='imagem',
            field=models.ImageField(default='media/imagens/default_pic.jpg', upload_to='media/imagens/', verbose_name='Upload da imagem'),
        ),
    ]
