# Generated by Django 2.2.7 on 2019-11-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20191110_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemperfil',
            name='nome',
            field=models.CharField(default='Nome da imagem', max_length=100),
        ),
    ]
